# 1. Usamos una imagen ligera de Python 3.11
FROM python:3.11-slim

# 2. Variables de entorno
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 3. Directorio de trabajo
WORKDIR /app

# 4. Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

# 5. Instalar librerías de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# --- [CAMBIO IMPORTANTE] ---
# Eliminamos la descarga manual. 
# Al hacer el COPY siguiente, Docker copiará tu carpeta local "model_files" 
# con el modelo ya descargado.

# 6. Copiar TODO el código (incluyendo la carpeta model_files y los .pkl)
COPY . .

# 7. Exponer puerto
EXPOSE 8080

# 8. Arrancar
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]